import Footer from "@/components/footer"
import Navbar from "@/components/navbar"
import "./../globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Suspense } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <section className="w-full  mt-20">
          <Suspense>
             {children}
          </Suspense>
         
          <ToastContainer position="top-center" autoClose={3000} />
        </section>
        <Footer/>
        </body>
    </html>
  )
}
