import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Providers from "../providers";



export const metadata = {
  title: "ResumeIQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white  `}>
      
        <Providers>{children}</Providers>
        <Footer/>
      </body>
    </html>
  );
}
